"""Add embedding column to document_chunks

Revision ID: 30967e1d5b0e
Revises: c6bef1600f1a
Create Date: 2026-07-16 06:16:24.855014
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30967e1d5b0e"
down_revision: str | None = "c6bef1600f1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_chunks", sa.Column("embedding", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "embedding")
    # ### end Alembic commands ###
